import type { Category, Priority, Profile, Resource, Status, Task, Topic } from "./prep-types";

let seq = 0;
const nextId = (prefix: string) => `${prefix}-${++seq}`;

type TopicSeed = [name: string, priority: Priority, hours: number, status?: Status];

function topics(category: Category, seeds: TopicSeed[]): Topic[] {
  return seeds.map(([name, priority, hours, status = "Not Started"]) => ({
    id: nextId("topic"),
    name,
    category,
    priority,
    hours,
    status,
  }));
}

export const initialTopics: Topic[] = [
  ...topics("Aptitude", [
    ["Number System", "High", 3, "Completed"],
    ["Percentages", "High", 3, "Completed"],
    ["Profit and Loss", "High", 3, "Completed"],
    ["Ratio and Proportion", "Medium", 2, "Completed"],
    ["Averages", "Medium", 2, "In Progress"],
    ["Time and Work", "High", 3],
    ["Time, Speed and Distance", "High", 3],
    ["Probability", "Medium", 3],
    ["Permutation and Combination", "Medium", 3],
    ["Data Interpretation", "High", 4],
  ]),
  ...topics("DSA", [
    ["Arrays", "High", 6, "Completed"],
    ["Strings", "High", 5, "Completed"],
    ["Linked Lists", "High", 5, "Completed"],
    ["Stack", "Medium", 4, "Completed"],
    ["Queue", "Medium", 3, "In Progress"],
    ["Hashing", "High", 4],
    ["Recursion", "High", 5],
    ["Trees", "High", 8],
    ["Graphs", "High", 9],
    ["Sorting", "Medium", 4],
    ["Searching", "Medium", 3],
    ["Dynamic Programming", "High", 10],
  ]),
  ...topics("SQL", [
    ["SELECT", "High", 2, "Completed"],
    ["WHERE", "High", 2, "Completed"],
    ["ORDER BY", "Medium", 1, "Completed"],
    ["GROUP BY", "High", 2, "Completed"],
    ["JOIN", "High", 4, "In Progress"],
    ["Subqueries", "High", 3],
    ["Aggregate Functions", "Medium", 2],
    ["Constraints", "Low", 2],
    ["Views", "Low", 1],
    ["Window Functions", "Medium", 3],
  ]),
  ...topics("React", [
    ["Components", "High", 3, "Completed"],
    ["Props", "High", 2, "Completed"],
    ["State", "High", 3, "Completed"],
    ["Hooks", "High", 5, "In Progress"],
    ["Forms", "Medium", 3],
    ["Routing", "Medium", 3],
    ["API Integration", "High", 4],
    ["Context", "Medium", 3],
    ["Performance", "Low", 3],
  ]),
  ...topics("Backend", [
    ["HTTP", "High", 2, "Completed"],
    ["REST APIs", "High", 4, "Completed"],
    ["Node.js", "High", 5, "In Progress"],
    ["Express", "High", 4],
    ["Authentication", "High", 4],
    ["Databases", "High", 5],
    ["API Design", "Medium", 3],
    ["Error Handling", "Medium", 2],
    ["Deployment", "Low", 3],
  ]),
  ...topics("Projects", [
    ["Project Planning", "Medium", 2, "Completed"],
    ["Git and GitHub", "High", 3, "Completed"],
    ["Documentation", "Low", 2, "In Progress"],
    ["Deployment", "Medium", 3],
    ["Portfolio Preparation", "High", 4],
  ]),
];

const today = new Date();
const iso = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
};

export const initialTasks: Task[] = [
  {
    id: nextId("task"),
    title: "Quantitative Aptitude — Percentages revision",
    category: "Aptitude",
    topic: "Percentages",
    priority: "High",
    minutes: 45,
    dueDate: iso(0),
    status: "Completed",
    today: true,
  },
  {
    id: nextId("task"),
    title: "SQL — SELECT and WHERE drills",
    category: "SQL",
    topic: "WHERE",
    priority: "High",
    minutes: 30,
    dueDate: iso(0),
    status: "Completed",
    today: true,
  },
  {
    id: nextId("task"),
    title: "DSA — Arrays: two pointers set",
    category: "DSA",
    topic: "Arrays",
    priority: "High",
    minutes: 60,
    dueDate: iso(0),
    status: "In Progress",
    today: true,
  },
  {
    id: nextId("task"),
    title: "React — Components and props practice",
    category: "React",
    topic: "Components",
    priority: "Medium",
    minutes: 40,
    dueDate: iso(0),
    status: "Not Started",
    today: true,
  },
  {
    id: nextId("task"),
    title: "Backend — Build a REST endpoint in Express",
    category: "Backend",
    topic: "Express",
    priority: "High",
    minutes: 50,
    dueDate: iso(1),
    status: "Not Started",
  },
  {
    id: nextId("task"),
    title: "DSA — Linked list reversal problems",
    category: "DSA",
    topic: "Linked Lists",
    priority: "Medium",
    minutes: 45,
    dueDate: iso(2),
    status: "Not Started",
  },
  {
    id: nextId("task"),
    title: "SQL — JOIN practice on sample schema",
    category: "SQL",
    topic: "JOIN",
    priority: "High",
    minutes: 40,
    dueDate: iso(3),
    status: "Not Started",
  },
  {
    id: nextId("task"),
    title: "Projects — Write README for portfolio app",
    category: "Projects",
    topic: "Documentation",
    priority: "Low",
    minutes: 30,
    dueDate: iso(4),
    status: "Not Started",
  },
  {
    id: nextId("task"),
    title: "Aptitude — Time and Work mock set",
    category: "Aptitude",
    topic: "Time and Work",
    priority: "Medium",
    minutes: 35,
    dueDate: iso(-1),
    status: "Completed",
  },
  {
    id: nextId("task"),
    title: "React — useEffect cleanup notes",
    category: "React",
    topic: "Hooks",
    priority: "Medium",
    minutes: 25,
    dueDate: iso(-2),
    status: "Completed",
  },
];

export const initialResources: Resource[] = [
  {
    id: nextId("res"),
    title: "Quantitative Aptitude Crash Course",
    category: "Aptitude",
    type: "YouTube",
    description: "Ten-hour walkthrough of percentages, ratios, averages and speed maths shortcuts.",
    url: "https://example.com/aptitude-crash-course",
    difficulty: "Beginner",
  },
  {
    id: nextId("res"),
    title: "Data Interpretation Problem Sets",
    category: "Aptitude",
    type: "Practice",
    description: "Timed sets of tables, bar charts and caselets modelled on campus tests.",
    url: "https://example.com/di-sets",
    difficulty: "Intermediate",
  },
  {
    id: nextId("res"),
    title: "Pattern-Based DSA Sheet",
    category: "DSA",
    type: "Practice",
    description: "150 problems grouped by pattern: sliding window, two pointers, trees, graphs, DP.",
    url: "https://example.com/dsa-sheet",
    difficulty: "Intermediate",
  },
  {
    id: nextId("res"),
    title: "Graphs from Scratch",
    category: "DSA",
    type: "Course",
    description: "BFS, DFS, topological sort and shortest paths with dry-run walkthroughs.",
    url: "https://example.com/graphs-course",
    difficulty: "Advanced",
  },
  {
    id: nextId("res"),
    title: "My DSA Revision Notes",
    category: "DSA",
    type: "Notes",
    description: "Condensed complexity tables and edge cases to reread the night before a test.",
    url: "https://example.com/dsa-notes",
    difficulty: "Beginner",
  },
  {
    id: nextId("res"),
    title: "SQL Joins Explained Visually",
    category: "SQL",
    type: "YouTube",
    description: "Inner, outer and self joins drawn out with small student-record tables.",
    url: "https://example.com/sql-joins",
    difficulty: "Beginner",
  },
  {
    id: nextId("res"),
    title: "PostgreSQL Window Functions Guide",
    category: "SQL",
    type: "Documentation",
    description: "Official reference for RANK, LAG, LEAD and framing clauses with examples.",
    url: "https://example.com/window-functions",
    difficulty: "Advanced",
  },
  {
    id: nextId("res"),
    title: "50 SQL Interview Queries",
    category: "SQL",
    type: "Practice",
    description: "Query challenges from real interview rounds, ordered by difficulty.",
    url: "https://example.com/sql-queries",
    difficulty: "Intermediate",
  },
  {
    id: nextId("res"),
    title: "React Official Learn Guide",
    category: "React",
    type: "Documentation",
    description: "Components, state, effects and the rules of hooks, straight from the docs.",
    url: "https://example.com/react-learn",
    difficulty: "Beginner",
  },
  {
    id: nextId("res"),
    title: "Hooks Deep Dive",
    category: "React",
    type: "Course",
    description: "useEffect dependencies, custom hooks, memoisation and render behaviour.",
    url: "https://example.com/hooks-deep-dive",
    difficulty: "Intermediate",
  },
  {
    id: nextId("res"),
    title: "Node and Express API Blueprint",
    category: "Backend",
    type: "Course",
    description: "Build a routed, validated REST API with auth middleware and error handling.",
    url: "https://example.com/express-blueprint",
    difficulty: "Intermediate",
  },
  {
    id: nextId("res"),
    title: "HTTP and REST Fundamentals",
    category: "Backend",
    type: "Notes",
    description: "Status codes, verbs, idempotency and headers in one printable page.",
    url: "https://example.com/http-notes",
    difficulty: "Beginner",
  },
  {
    id: nextId("res"),
    title: "Auth Patterns for Interviews",
    category: "Backend",
    type: "Documentation",
    description: "Sessions vs tokens, refresh rotation and common follow-up questions.",
    url: "https://example.com/auth-patterns",
    difficulty: "Advanced",
  },
  {
    id: nextId("res"),
    title: "Git and GitHub for Students",
    category: "Projects",
    type: "YouTube",
    description: "Branching, pull requests and cleaning history before a recruiter reads it.",
    url: "https://example.com/git-students",
    difficulty: "Beginner",
  },
  {
    id: nextId("res"),
    title: "Portfolio Project Checklist",
    category: "Projects",
    type: "Notes",
    description: "Scoping, README structure, deployment and what to demo in five minutes.",
    url: "https://example.com/portfolio-checklist",
    difficulty: "Intermediate",
  },
];

export const initialProfile: Profile = {
  name: "Dev Rathi",
  college: "Sardar Patel Institute of Technology",
  branch: "Computer Science and Engineering",
  graduationYear: "2027",
  targetRole: "Software Engineer (Full Stack)",
  skills: ["JavaScript", "TypeScript", "React", "Node.js", "SQL", "Data Structures"],
};

export const weeklyMinutes = [
  { day: "Mon", minutes: 95 },
  { day: "Tue", minutes: 120 },
  { day: "Wed", minutes: 60 },
  { day: "Thu", minutes: 145 },
  { day: "Fri", minutes: 80 },
  { day: "Sat", minutes: 165 },
  { day: "Sun", minutes: 45 },
];

export const recentActivity = [
  { label: "Completed Percentages revision", meta: "Aptitude · 2 hours ago" },
  { label: "Marked SELECT and WHERE as done", meta: "SQL · 5 hours ago" },
  { label: "Started Arrays two-pointer set", meta: "DSA · yesterday" },
  { label: "Added README task for portfolio app", meta: "Projects · yesterday" },
  { label: "Finished Hooks cleanup notes", meta: "React · 2 days ago" },
];

export const currentStreak = 12;
export const bestStreak = 19;
export const weeklyGoalTasks = 14;
export const placementWindowDays = 42;
